name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          # - public_access (default scope)
          # - read:user
          # - read:org
          # The following additional scopes may be required:
          # - read:org (for organization related metrics)
          # - read:user (for user related data)
          # - read:packages (for some packages related data)
          # - repo (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: spacebot-fcc
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          plugin_16personalities: yes
          plugin_16personalities_scores: yes
          plugin_16personalities_sections: personality
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_anilist: yes
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites
          plugin_anilist_shuffle: yes
          plugin_anilist_user: .user.login
          plugin_calendar: yes
          plugin_calendar_limit: 1
          plugin_chess: yes
          plugin_chess_animation: '{ "size": 40, "delay": 3, "duration": 0.6 }'
          plugin_chess_user: .user.login
          plugin_discussions: yes
          plugin_discussions_categories: yes
          plugin_fortune: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_leetcode: yes
          plugin_leetcode_limit_recent: 2
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_sections: solved
          plugin_leetcode_user: .user.login
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_music: yes
          plugin_music_limit: 4
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_user: .user.login
          plugin_nightscout: yes
          plugin_nightscout_datapoints: 12
          plugin_nightscout_highalert: 180
          plugin_nightscout_lowalert: 80
          plugin_nightscout_urgenthighalert: 250
          plugin_nightscout_urgentlowalert: 50
          plugin_nightscout_url: https://example.herokuapp.com
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          plugin_pagespeed: yes
          plugin_pagespeed_url: .user.website
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_poopmap: yes
          plugin_poopmap_days: 7
          plugin_posts: yes
          plugin_posts_limit: 4
          plugin_posts_user: .user.login
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          plugin_rss: yes
          plugin_rss_limit: 4
          plugin_screenshot: yes
          plugin_screenshot_background: yes
          plugin_screenshot_mode: image
          plugin_screenshot_selector: body
          plugin_screenshot_title: Screenshot
          plugin_screenshot_viewport: '{ "width": 1280, "height": 1280 }'
          plugin_splatoon: yes
          plugin_splatoon_salmon_limit: 1
          plugin_splatoon_sections: player, versus, salmon-run
          plugin_splatoon_source: splatnet
          plugin_splatoon_versus_limit: 1
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list, about
          plugin_sponsors_size: 24
          plugin_sponsors_title: Sponsor Me!
          plugin_sponsorships: yes
          plugin_sponsorships_sections: amount, sponsorships
          plugin_sponsorships_size: 24
          plugin_stackoverflow: yes
          plugin_stackoverflow_limit: 2
          plugin_stackoverflow_lines: 4
          plugin_stackoverflow_lines_snippet: 2
          plugin_stackoverflow_sections: answers-top, questions-recent
          plugin_starlists: yes
          plugin_starlists_limit: 2
          plugin_starlists_limit_languages: 8
          plugin_starlists_limit_repositories: 2
          plugin_starlists_shuffle_repositories: yes
          plugin_steam: yes
          plugin_steam_achievements_limit: 2
          plugin_steam_games_limit: 1
          plugin_steam_playtime_threshold: 2
          plugin_steam_recent_games_limit: 1
          plugin_steam_sections: player, most-played, recently-played
          plugin_stock: yes
          plugin_stock_duration: 1d
          plugin_stock_interval: 5m
          plugin_tweets: yes
          plugin_tweets_limit: 2
          plugin_tweets_user: .user.twitter
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: current
